pub mod connector;
pub mod transport;
pub use connector::{Connector,ConnectorManifest,PollHandle,RateLimits,SyncState};
use orbit_core::{OwnerScope,AuthorizedAction,Error,Result};
use orbit_secrets::SecretStore;
use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use sqlx::{PgPool,Row};
use uuid::Uuid;
use sha2::{Digest,Sha256};
use base64::{Engine,engine::general_purpose::STANDARD};
use std::time::Duration;
pub const MAX_MESSAGE_BYTES:usize=1024*1024;
/// Quarantine store guard: inbound bodies/attachments + uploaded bytes land hashed, size-bounded, MIME-sniffed, and blocked on path-traversal / archive-bomb patterns.
pub const MAX_QUARANTINE_BYTES:usize=10*1024*1024;
#[derive(Debug,Clone,serde::Serialize,serde::Deserialize)]
pub struct QuarantinedBlob{pub sha256:String,pub size:usize,pub mime:String,pub name:String}
pub fn sniff_mime(name:&str,bytes:&[u8])->String{if bytes.len()>=4&&bytes[0]==0x50&&bytes[1]==0x4B&&(bytes[2]==0x03||bytes[2]==0x05||bytes[2]==0x07){return "application/zip".into()}if bytes.len()>=6&&(bytes.starts_with(b"GIF87a")||bytes.starts_with(b"GIF89a")){return "image/gif".into()}if bytes.len()>=4&&bytes[0]==0x89&&bytes[1]==0x50&&bytes[2]==0x4E&&bytes[3]==0x47{return "image/png".into()}if bytes.len()>=3&&bytes[0]==0xFF&&bytes[1]==0xD8&&bytes[2]==0xFF{return "image/jpeg".into()}if bytes.len()>=5&&bytes.starts_with(b"%PDF-"){return "application/pdf".into()}if bytes.iter().all(|b|*b==b'\n'||*b==b'\r'||*b==b'\t'||(0x20..=0x7E).contains(b)||*b>=0x80){let ext=name.rsplit('.').next().unwrap_or("").to_ascii_lowercase();return match ext.as_str(){"txt"|"md"|"csv"|"json"|"eml" =>format!("text/{ext}"),_=>"text/plain".into()}} "application/octet-stream".into()}
pub fn quarantine_store(name:&str,claimed_mime:&str,bytes:&[u8])->Result<QuarantinedBlob>{if bytes.len()>MAX_QUARANTINE_BYTES||bytes.len()>MAX_MESSAGE_BYTES*10{return Err(Error::Validation("quarantined blob exceeds size bound".into()))}if name.is_empty()||name.len()>256||name.contains(['\0','\\'])||name.contains("..")||name.starts_with('/')||name.contains(':'){return Err(Error::Validation("quarantined name fails path-traversal screen".into()))}let sniffed=sniff_mime(name,bytes);if sniffed=="application/zip"&&bytes.windows(2).filter(|w|w==b"PK").count()>512{return Err(Error::Validation("quarantined archive fails bomb screen".into()))}let safe:String=name.chars().filter(|c|c.is_ascii_alphanumeric()||matches!(c,'_'|'-'|'.'|' ')).take(120).collect();let safe=safe.trim().trim_matches('.');let safe=if safe.is_empty(){"attachment.bin"}else{safe};let mime=if claimed_mime.len()<=120&&claimed_mime.bytes().all(|c|c.is_ascii_graphic()){claimed_mime}else{&sniffed};Ok(QuarantinedBlob{sha256:hex::encode(Sha256::digest(bytes)),size:bytes.len(),mime:mime.into(),name:safe.into()})}
#[derive(Clone,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AccountConfig{pub imap_host:String,pub imap_port:u16,pub smtp_host:String,pub smtp_port:u16,pub from_address:String,pub mailboxes:Vec<String>,pub archive_mailbox:Option<String>,#[serde(default="poll_default")]pub poll_seconds:u64,pub ca_pem:Option<String>}
fn poll_default()->u64{60}
impl AccountConfig{pub fn validate(&self)->Result<()>{if self.mailboxes.is_empty()||self.mailboxes.len()>20||!(15..=3600).contains(&self.poll_seconds)||self.imap_port==0||self.smtp_port==0{return Err(Error::Validation("invalid bounded mailbox configuration".into()))}address(&self.from_address)?;for h in [&self.imap_host,&self.smtp_host]{if h.is_empty()||h.len()>253||h.chars().any(|c|c.is_whitespace()||c=='/'||c=='@'){return Err(Error::Validation("invalid mail hostname".into()))}}for m in &self.mailboxes{if m.is_empty()||m.len()>256||m.chars().any(char::is_control){return Err(Error::Validation("invalid mailbox scope".into()))}}if self.ca_pem.as_ref().is_some_and(|s|s.len()>65536){return Err(Error::Validation("CA certificate exceeds bound".into()))}Ok(())}}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Credential{pub username:String,pub password:String}
impl Drop for Credential{fn drop(&mut self){use zeroize::Zeroize;self.username.zeroize();self.password.zeroize();}}
#[derive(Clone,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Attachment{pub name:String,pub mime:String,pub sha256:String,pub content_base64:String}
#[derive(Clone,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DraftContent{pub from:String,pub to:Vec<String>,#[serde(default)]pub cc:Vec<String>,#[serde(default)]pub bcc:Vec<String>,pub subject:String,pub body:String,pub in_reply_to:Option<String>,#[serde(default)]pub references:Vec<String>,#[serde(default)]pub attachments:Vec<Attachment>}
fn address(s:&str)->Result<()>{let parts:Vec<_>=s.split('@').collect();if parts.len()!=2||parts.iter().any(|s|s.is_empty())||s.len()>254||s.bytes().any(|b|!b.is_ascii_alphanumeric()&&!b".!#$%&'*+-/=?^_`{|}~@".contains(&b)){return Err(Error::Validation("email address must be one plain addr-spec".into()))}Ok(())}
fn header(s:&str)->Result<()>{if s.len()>4096||s.chars().any(char::is_control){return Err(Error::Validation("unsafe email header".into()))}Ok(())}
impl DraftContent{pub fn validate(&self)->Result<()>{address(&self.from)?;if self.to.is_empty()||self.to.len()+self.cc.len()+self.bcc.len()>50||self.body.len()>MAX_MESSAGE_BYTES||self.attachments.len()>20{return Err(Error::Validation("draft exceeds bounds".into()))}for a in self.to.iter().chain(&self.cc).chain(&self.bcc){address(a)?}header(&self.subject)?;if let Some(s)=&self.in_reply_to{header(s)?}for s in &self.references{header(s)?}let mut total=self.body.len();for a in &self.attachments{header(&a.name)?;header(&a.mime)?;if a.name.is_empty()||a.name.contains(['"','\\','/'])||!a.mime.contains('/')||a.mime.contains(['"',';',' '])||a.content_base64.len()>MAX_MESSAGE_BYTES*4/3+4{return Err(Error::Validation("invalid MIME attachment".into()))}let bytes=STANDARD.decode(&a.content_base64).map_err(|_|Error::Validation("invalid attachment encoding".into()))?;total+=bytes.len();if total>MAX_MESSAGE_BYTES||a.sha256!=hex::encode(Sha256::digest(&bytes)){return Err(Error::Validation("attachment digest or size mismatch".into()))}}Ok(())}}
#[derive(Serialize,Deserialize)]
pub struct Message{pub message_id:String,pub source_key:String,pub metadata:Value,pub body_text:String,pub attachments:Vec<Attachment>,pub references:Vec<String>}
pub fn content_digest(content:&DraftContent)->Result<String>{Ok(hex::encode(Sha256::digest(serde_json::to_vec(content)?)))}
#[derive(Clone)]
pub struct MailService{pub pool:PgPool,pub secrets:SecretStore}
#[async_trait::async_trait]
pub trait EmailProvider:Send+Sync{async fn execute(&self,scope:&OwnerScope,action:&AuthorizedAction)->Result<Value>;}
impl MailService{
 pub async fn account(&self,scope:&OwnerScope,id:Uuid)->Result<(AccountConfig,Uuid,Uuid,i64)>{let row=sqlx::query("SELECT config,imap_secret_id,smtp_secret_id,revision FROM email_accounts WHERE owner_id=$1 AND id=$2 AND enabled").bind(scope.owner_id).bind(id).fetch_optional(&self.pool).await?.ok_or(Error::NotFound)?;Ok((serde_json::from_value(row.get("config"))?,row.get("imap_secret_id"),row.get("smtp_secret_id"),row.get("revision")))}
 async fn credential(&self,scope:&OwnerScope,id:Uuid)->Result<Credential>{let bytes=self.secrets.get(scope,id).await?;serde_json::from_slice(&bytes).map_err(|_|Error::Unavailable("mail credential configuration invalid".into()))}
 pub async fn test(&self,scope:&OwnerScope,id:Uuid)->Result<Value>{let(c,secret,_,_)=self.account(scope,id).await?;let credential=self.credential(scope,secret).await?;tokio::time::timeout(Duration::from_secs(30),async{let mut imap=transport::Imap::connect(&c,&credential).await?;for mailbox in &c.mailboxes{imap.select(mailbox).await?;}Ok(json!({"status":"CONNECTED","tls_verified":true,"mailboxes":c.mailboxes}))}).await.map_err(|_|Error::Timeout)?}
 pub async fn store_draft(&self,scope:&OwnerScope,account:Uuid,content:DraftContent)->Result<Value>{content.validate()?;let(c,_,_,_)=self.account(scope,account).await?;if content.from!=c.from_address{return Err(Error::Forbidden)}let id=Uuid::new_v4();let digest=content_digest(&content)?;let value=serde_json::to_value(content)?;let mut tx=self.pool.begin().await?;sqlx::query("INSERT INTO email_drafts(id,owner_id,account_id,content,content_digest) VALUES($1,$2,$3,$4,$5)").bind(id).bind(scope.owner_id).bind(account).bind(&value).bind(&digest).execute(&mut *tx).await?;sqlx::query("INSERT INTO email_draft_versions(owner_id,draft_id,version,content,content_digest) VALUES($1,$2,1,$3,$4)").bind(scope.owner_id).bind(id).bind(&value).bind(&digest).execute(&mut *tx).await?;tx.commit().await?;Ok(json!({"id":id,"account_id":account,"version":1,"content":value,"content_digest":digest,"state":"DRAFT"}))}
 pub async fn edit_draft(&self,scope:&OwnerScope,id:Uuid,expected:i64,content:DraftContent)->Result<Value>{content.validate()?;let digest=content_digest(&content)?;let value=serde_json::to_value(&content)?;let mut tx=self.pool.begin().await?;sqlx::query("SELECT revision FROM authorization_epochs WHERE owner_id=$1 FOR UPDATE").bind(scope.owner_id).fetch_one(&mut *tx).await?;let row=sqlx::query("SELECT d.account_id,a.config FROM email_drafts d JOIN email_accounts a ON a.owner_id=d.owner_id AND a.id=d.account_id WHERE d.owner_id=$1 AND d.id=$2 AND d.version=$3 AND d.state='DRAFT' AND a.enabled FOR UPDATE OF d").bind(scope.owner_id).bind(id).bind(expected).fetch_optional(&mut *tx).await?.ok_or_else(||Error::Conflict("draft changed or already submitted".into()))?;let config:AccountConfig=serde_json::from_value(row.get("config"))?;if content.from!=config.from_address{return Err(Error::Forbidden)}let account:Uuid=row.get("account_id");sqlx::query("UPDATE email_drafts SET version=version+1,content=$3,content_digest=$4,updated_at=now() WHERE owner_id=$1 AND id=$2").bind(scope.owner_id).bind(id).bind(&value).bind(&digest).execute(&mut *tx).await?;sqlx::query("INSERT INTO email_draft_versions(owner_id,draft_id,version,content,content_digest) VALUES($1,$2,$3,$4,$5)").bind(scope.owner_id).bind(id).bind(expected+1).bind(&value).bind(&digest).execute(&mut *tx).await?;sqlx::query("UPDATE authorization_epochs SET revision=revision+1 WHERE owner_id=$1").bind(scope.owner_id).execute(&mut *tx).await?;tx.commit().await?;Ok(json!({"id":id,"account_id":account,"version":expected+1,"content":value,"content_digest":digest,"state":"DRAFT"}))}
 /// Claim a bounded ingestion batch; no database lock crosses an IMAP operation.
 pub async fn sync(&self,scope:&OwnerScope,id:Uuid)->Result<Value>{
  let(c,secret,_,revision)=self.account(scope,id).await?;let holder=Uuid::new_v4();sqlx::query("INSERT INTO email_ingestion_leases(owner_id,account_id) VALUES($1,$2) ON CONFLICT DO NOTHING").bind(scope.owner_id).bind(id).execute(&self.pool).await?;
  let fence:Option<i64>=sqlx::query_scalar("UPDATE email_ingestion_leases SET lease_holder=$3,lease_until=now()+interval '120 seconds',fence=fence+1 WHERE owner_id=$1 AND account_id=$2 AND (lease_until IS NULL OR lease_until<now()) RETURNING fence").bind(scope.owner_id).bind(id).bind(holder).fetch_optional(&self.pool).await?;let fence=fence.ok_or_else(||Error::Conflict("mail sync already active".into()))?;
  let credential=self.credential(scope,secret).await?;let result=tokio::time::timeout(Duration::from_secs(90),self.sync_batch(scope,id,&c,&credential,revision,holder,fence)).await.map_err(|_|Error::Timeout).and_then(|r|r);
  sqlx::query("UPDATE email_ingestion_leases SET lease_until=NULL WHERE owner_id=$1 AND account_id=$2 AND lease_holder=$3 AND fence=$4").bind(scope.owner_id).bind(id).bind(holder).bind(fence).execute(&self.pool).await?;
  sqlx::query("UPDATE email_accounts SET last_sync=CASE WHEN $3 THEN now() ELSE last_sync END,last_error=CASE WHEN $3 THEN NULL ELSE 'Mail sync failed; repair verified connection' END WHERE owner_id=$1 AND id=$2").bind(scope.owner_id).bind(id).bind(result.is_ok()).execute(&self.pool).await?;result
 }
 async fn sync_batch(&self,scope:&OwnerScope,id:Uuid,c:&AccountConfig,credential:&Credential,revision:i64,holder:Uuid,fence:i64)->Result<Value>{
  let mut imap=transport::Imap::connect(c,credential).await?;let mut added=0;let mut rescanned=false;
  for mailbox in &c.mailboxes{
   let validity=imap.select(mailbox).await?;let checkpoint=sqlx::query("SELECT uidvalidity,last_uid FROM email_checkpoints WHERE owner_id=$1 AND account_id=$2 AND mailbox=$3").bind(scope.owner_id).bind(id).bind(mailbox).fetch_optional(&self.pool).await?;
   let last=checkpoint.as_ref().filter(|r|r.get::<i64,_>("uidvalidity")==validity).map(|r|r.get::<i64,_>("last_uid")).unwrap_or(0);if checkpoint.as_ref().is_some_and(|r|r.get::<i64,_>("uidvalidity")!=validity){rescanned=true}
   let uids=imap.search(last+1).await?;
   for uid in uids.into_iter().take(50){let raw=imap.fetch(uid).await?;let message=transport::parse_message(&raw)?;quarantine_store(&format!("email-body-{uid}.txt"),"text/plain",message.body_text.as_bytes())?;for a in &message.attachments{let bytes=STANDARD.decode(&a.content_base64).map_err(|_|Error::Validation("quarantined attachment undecodable".into()))?;let q=quarantine_store(&a.name,&a.mime,&bytes)?;if q.sha256!=a.sha256{return Err(Error::Conflict("quarantined attachment digest mismatch".into()))}}let mut tx=self.pool.begin().await?;
    sqlx::query("SELECT revision FROM authorization_epochs WHERE owner_id=$1 FOR UPDATE").bind(scope.owner_id).fetch_one(&mut *tx).await?;
    let live:bool=sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM email_accounts a JOIN email_ingestion_leases l ON l.owner_id=a.owner_id AND l.account_id=a.id WHERE a.owner_id=$1 AND a.id=$2 AND a.enabled AND a.revision=$3 AND l.lease_holder=$4 AND l.fence=$5 AND l.lease_until>now())").bind(scope.owner_id).bind(id).bind(revision).bind(holder).bind(fence).fetch_one(&mut *tx).await?;if !live{return Err(Error::Forbidden)}
    let msg=Uuid::new_v4();let inserted=sqlx::query("INSERT INTO email_messages(id,owner_id,account_id,mailbox,uidvalidity,uid,source_key,message_id,thread_references,metadata,body_text,attachments) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT DO NOTHING").bind(msg).bind(scope.owner_id).bind(id).bind(mailbox).bind(validity).bind(uid).bind(&message.source_key).bind(&message.message_id).bind(json!(message.references)).bind(&message.metadata).bind(&message.body_text).bind(json!(message.attachments)).execute(&mut *tx).await?.rows_affected()>0;
    sqlx::query("INSERT INTO email_checkpoints(owner_id,account_id,mailbox,uidvalidity,last_uid) VALUES($1,$2,$3,$4,$5) ON CONFLICT(owner_id,account_id,mailbox) DO UPDATE SET uidvalidity=excluded.uidvalidity,last_uid=excluded.last_uid").bind(scope.owner_id).bind(id).bind(mailbox).bind(validity).bind(uid).execute(&mut *tx).await?;
    if inserted{let principal=Uuid::new_v4();sqlx::query("INSERT INTO principals(id,owner_id,principal_type,auth_method,trust_level,source) VALUES($1,$2,'EMAIL_SENDER','VERIFIED_IMAP','UNTRUSTED_EXTERNAL',$3)").bind(principal).bind(scope.owner_id).bind(format!("email:{id}")).execute(&mut *tx).await?;let event=Uuid::new_v4();let source=format!("email:{id}");let kind=if message.metadata["in_reply_to"].as_str().is_some(){"EMAIL_REPLIED"}else{"EMAIL_RECEIVED"};sqlx::query("INSERT INTO events(id,owner_id,event_type,source,principal_id,payload,trust_level,privacy_class,correlation_id,source_event_key) VALUES($1,$2,$3,$4,$5,$6,'UNTRUSTED_EXTERNAL','PRIVATE',$7,$8)").bind(event).bind(scope.owner_id).bind(kind).bind(source).bind(principal).bind(json!({"message_id":msg,"account_id":id,"source_reference":format!("email:{id}:{msg}")})).bind(event).bind(&message.source_key).execute(&mut *tx).await?;sqlx::query("INSERT INTO event_deliveries(id,owner_id,event_id,consumer) VALUES($1,$2,$3,'agents') ON CONFLICT DO NOTHING").bind(Uuid::new_v4()).bind(scope.owner_id).bind(event).execute(&mut *tx).await?;added+=1;}
    tx.commit().await?;
   }
  }Ok(json!({"received":added,"uidvalidity_rescan":rescanned,"batch_limit":50}))
 }
 pub async fn materialize_send(&self,scope:&OwnerScope,args:&Value)->Result<(Value,std::collections::BTreeMap<String,i64>,std::collections::BTreeMap<String,String>)>{let id=uuid_field(args,"draft_id")?;let version=args["expected_version"].as_i64().ok_or_else(||Error::Validation("draft version required".into()))?;let row=sqlx::query("SELECT account_id,content,content_digest FROM email_drafts WHERE owner_id=$1 AND id=$2 AND version=$3 AND state='DRAFT'").bind(scope.owner_id).bind(id).bind(version).fetch_optional(&self.pool).await?.ok_or_else(||Error::Conflict("draft version changed or already submitted".into()))?;let account:Uuid=row.get("account_id");let(_,_,_,rev)=self.account(scope,account).await?;let content:Value=row.get("content");let draft:DraftContent=serde_json::from_value(content.clone())?;let mut digests=std::collections::BTreeMap::new();for a in &draft.attachments{digests.insert(a.name.clone(),a.sha256.clone());}Ok((json!({"draft_id":id,"expected_version":version,"account_id":account,"content":content,"content_digest":row.get::<String,_>("content_digest")}),[(format!("email_account:{account}"),rev),(format!("email_draft:{id}"),version)].into(),digests))}
}
pub fn uuid_field(v:&Value,key:&str)->Result<Uuid>{v[key].as_str().and_then(|s|Uuid::parse_str(s).ok()).ok_or_else(||Error::Validation(format!("{key} required")))}
#[async_trait::async_trait]
impl EmailProvider for MailService{
 async fn execute(&self,scope:&OwnerScope,action:&AuthorizedAction)->Result<Value>{
  let snapshot=action.snapshot();if snapshot.owner_id!=scope.owner_id{return Err(Error::Forbidden)}let args=&snapshot.arguments;
  if snapshot.tool_name=="email.send"{
   let draft_id=uuid_field(args,"draft_id")?;let account=uuid_field(args,"account_id")?;let expected=args["expected_version"].as_i64().ok_or(Error::Forbidden)?;let draft:DraftContent=serde_json::from_value(args["content"].clone())?;draft.validate()?;let digest=content_digest(&draft)?;if args["content_digest"]!=digest{return Err(Error::Forbidden)}let(c,_,secret,_)=self.account(scope,account).await?;if draft.from!=c.from_address{return Err(Error::Forbidden)}let credential=self.credential(scope,secret).await?;
   let changed=sqlx::query("UPDATE email_drafts SET state='SUBMITTED',authorization_id=$5,smtp_evidence=jsonb_build_object('message_id',$6::text),updated_at=now() WHERE owner_id=$1 AND id=$2 AND account_id=$3 AND version=$4 AND state='DRAFT' AND content_digest=$7").bind(scope.owner_id).bind(draft_id).bind(account).bind(expected).bind(action.authorization_id()).bind(format!("<{draft_id}@orbit.invalid>")).bind(digest).execute(&self.pool).await?.rows_affected();if changed!=1{return Err(Error::Conflict("SMTP draft submission cannot be replayed".into()))}
   let result=tokio::time::timeout(Duration::from_secs(30),transport::send_once(&c,&credential,&draft,draft_id)).await.map_err(|_|Error::OutcomeUnknown).and_then(|r|r);let state=match &result{Ok(_)=>"SENT",Err(Error::OutcomeUnknown)=>"OUTCOME_UNKNOWN",Err(_)=>"FAILED"};sqlx::query("UPDATE email_drafts SET state=$3,updated_at=now() WHERE owner_id=$1 AND id=$2 AND authorization_id=$4 AND state='SUBMITTED'").bind(scope.owner_id).bind(draft_id).bind(state).bind(action.authorization_id()).execute(&self.pool).await?;result?;return Ok(json!({"draft_id":draft_id,"state":"SENT","message_id":format!("<{draft_id}@orbit.invalid>")}))
  }
  let account=uuid_field(args,"account_id")?;let(c,secret,_,_)=self.account(scope,account).await?;
  match snapshot.tool_name.as_str(){
   "email.draft"=>self.store_draft(scope,account,serde_json::from_value(args["content"].clone())?).await,
   "email.search"=>{let query=args["query"].as_str().unwrap_or("");let rows=sqlx::query_scalar::<_,Value>("SELECT jsonb_build_object('id',id,'account_id',account_id,'metadata',metadata,'privacy_class',privacy_class,'trust_level',trust_level) FROM email_messages WHERE owner_id=$1 AND account_id=$2 AND (metadata::text ILIKE $3 OR body_text ILIKE $3) ORDER BY received_at DESC,id DESC LIMIT 50").bind(scope.owner_id).bind(account).bind(format!("%{query}%")).fetch_all(&self.pool).await?;Ok(json!({"items":rows,"next_cursor":null}))},
   "email.read"=>{let message=uuid_field(args,"message_id")?;let value=sqlx::query_scalar("SELECT jsonb_build_object('id',id,'account_id',account_id,'metadata',metadata,'body_text',body_text,'attachments',attachments,'authentication',authentication,'privacy_class',privacy_class,'trust_level',trust_level,'source_reference','email:'||account_id::text||':'||id::text) FROM email_messages WHERE owner_id=$1 AND account_id=$2 AND id=$3").bind(scope.owner_id).bind(account).bind(message).fetch_optional(&self.pool).await?.ok_or(Error::NotFound)?;Ok(value)},
   "email.archive"|"email.label"=>{let message=uuid_field(args,"message_id")?;let row=sqlx::query("SELECT mailbox,uidvalidity,uid FROM email_messages WHERE owner_id=$1 AND account_id=$2 AND id=$3").bind(scope.owner_id).bind(account).bind(message).fetch_optional(&self.pool).await?.ok_or(Error::NotFound)?;let mailbox:String=row.get("mailbox");if !c.mailboxes.contains(&mailbox){return Err(Error::Forbidden)}let credential=self.credential(scope,secret).await?;tokio::time::timeout(Duration::from_secs(30),async{let mut imap=transport::Imap::connect(&c,&credential).await?;if imap.select(&mailbox).await?!=row.get::<i64,_>("uidvalidity"){return Err(Error::Conflict("mailbox UIDVALIDITY changed".into()))}let uid=row.get("uid");if snapshot.tool_name=="email.archive"{imap.archive(uid,c.archive_mailbox.as_deref().ok_or(Error::UnsupportedCapability)?).await.map_err(|_|Error::OutcomeUnknown)?;}else{imap.label(uid,args["label"].as_str().ok_or(Error::UnsupportedCapability)?).await.map_err(|_|Error::OutcomeUnknown)?;}Ok(json!({"message_id":message,"outcome":"APPLIED"}))}).await.map_err(|_|Error::OutcomeUnknown)?},
   _=>Err(Error::UnsupportedCapability)
  }
 }
}
/// Recovery only marks abandoned SMTP submissions uncertain; never retransmits.
pub async fn recover_submissions(pool:&PgPool)->Result<()>{sqlx::query("UPDATE email_drafts SET state='OUTCOME_UNKNOWN' WHERE state='SUBMITTED' AND updated_at<now()-interval '2 minutes'").execute(pool).await?;Ok(())}
pub async fn poll(pool:&PgPool,key_dir:&std::path::Path)->Result<()>{recover_submissions(pool).await?;let service=MailService{pool:pool.clone(),secrets:SecretStore::open(pool.clone(),key_dir).await?};let rows=sqlx::query("SELECT a.owner_id,a.id,p.id principal_id FROM email_accounts a JOIN LATERAL (SELECT id FROM principals WHERE owner_id=a.owner_id AND principal_type='WEB_USER' LIMIT 1) p ON true WHERE a.enabled AND (a.last_sync IS NULL OR a.last_sync<now()-make_interval(secs=>(a.config->>'poll_seconds')::integer))").fetch_all(pool).await?;for r in rows{let scope=OwnerScope{owner_id:r.get("owner_id"),principal_id:r.get("principal_id")};let _=service.sync(&scope,r.get("id")).await;}Ok(())}
