DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'orbit_runtime') THEN
    CREATE ROLE orbit_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD 'orbit_runtime_fixture';
  END IF;
END $$;
ALTER ROLE orbit_runtime WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD 'orbit_runtime_fixture';
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO orbit_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orbit_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orbit_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE orbit_test IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orbit_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE orbit_test IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO orbit_runtime;
DO $$ BEGIN
  IF to_regclass('public.audit_events') IS NOT NULL THEN
    REVOKE UPDATE, DELETE, TRUNCATE ON TABLE public.audit_events FROM orbit_runtime;
    GRANT SELECT, INSERT ON TABLE public.audit_events TO orbit_runtime;
  END IF;
END $$;
