CREATE DATABASE orbit_e2e OWNER orbit_test;
CREATE ROLE orbit_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD 'orbit_runtime_fixture';
\connect orbit_e2e
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO orbit_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE orbit_test IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orbit_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE orbit_test IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO orbit_runtime;
