[package]
name = "orbit-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
orbit-api = { path = "../../crates/api" }
tokio.workspace = true
sqlx.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true
axum.workspace = true
