CREATE TABLE agent_definitions(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),definition jsonb NOT NULL,revision bigint NOT NULL DEFAULT 1,enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id));
CREATE TABLE conversations(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),agent_id uuid NOT NULL,title text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),FOREIGN KEY(owner_id,agent_id) REFERENCES agent_definitions(owner_id,id));
CREATE TABLE chat_attachments(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),name text NOT NULL,mime_type text NOT NULL,size bigint NOT NULL CHECK(size BETWEEN 0 AND 10485760),sha256 text NOT NULL,storage_key text NOT NULL,privacy_class text NOT NULL DEFAULT 'PRIVATE',trust_level text NOT NULL DEFAULT 'UNTRUSTED_EXTERNAL',source_reference jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id));
CREATE TABLE chat_messages(id uuid PRIMARY KEY,owner_id uuid NOT NULL,conversation_id uuid NOT NULL,task_id uuid,role text NOT NULL CHECK(role IN ('user','assistant','tool')),content text NOT NULL,attachments jsonb NOT NULL DEFAULT '[]',route jsonb,tool_calls jsonb NOT NULL DEFAULT '[]',turn_key text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),UNIQUE(owner_id,task_id,turn_key),FOREIGN KEY(owner_id,conversation_id) REFERENCES conversations(owner_id,id),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id));
CREATE INDEX chat_messages_conversation ON chat_messages(owner_id,conversation_id,created_at,id);
CREATE TABLE agent_runs(task_id uuid PRIMARY KEY,owner_id uuid NOT NULL,agent_id uuid NOT NULL,conversation_id uuid NOT NULL,definition jsonb NOT NULL,phase text NOT NULL DEFAULT 'CONTEXT',turn integer NOT NULL DEFAULT 0,context jsonb NOT NULL DEFAULT '[]',chat jsonb NOT NULL DEFAULT '{}',model_response jsonb,route jsonb,model_call_id uuid,pending_calls jsonb NOT NULL DEFAULT '[]',proposal_index integer NOT NULL DEFAULT 0,model_calls integer NOT NULL DEFAULT 0,tool_calls integer NOT NULL DEFAULT 0,tokens bigint NOT NULL DEFAULT 0,active_seconds double precision NOT NULL DEFAULT 0,model_retries integer NOT NULL DEFAULT 0,failure_counts jsonb NOT NULL DEFAULT '{}',depth integer NOT NULL DEFAULT 0,automatic boolean NOT NULL DEFAULT false,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,task_id),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id),FOREIGN KEY(owner_id,agent_id) REFERENCES agent_definitions(owner_id,id),FOREIGN KEY(owner_id,conversation_id) REFERENCES conversations(owner_id,id));
CREATE TABLE agent_tool_aliases(owner_id uuid NOT NULL,task_id uuid NOT NULL,alias text NOT NULL CHECK(alias ~ '^t_[a-f0-9]{32}$'),tool_id uuid NOT NULL,tool_name text NOT NULL,tool_version text NOT NULL,input_schema jsonb NOT NULL,PRIMARY KEY(owner_id,task_id,alias),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id));
CREATE INDEX agent_runs_owner ON agent_runs(owner_id,agent_id);
ALTER TABLE chat_messages ADD COLUMN tool_call_id text;
