CREATE TABLE policies(owner_id uuid PRIMARY KEY REFERENCES users(id),revision bigint NOT NULL DEFAULT 1,rules jsonb NOT NULL DEFAULT '[]',max_tool_calls integer NOT NULL DEFAULT 24 CHECK(max_tool_calls BETWEEN 1 AND 1000),max_active_seconds integer NOT NULL DEFAULT 600 CHECK(max_active_seconds BETWEEN 1 AND 86400));
CREATE TABLE scope_grants(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),tool_name text NOT NULL,scope_key text NOT NULL,scope_revision bigint NOT NULL,max_risk text NOT NULL CHECK(max_risk IN('READ_ONLY','LOW')),autonomy_modes jsonb NOT NULL,parameter_bounds jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),UNIQUE(owner_id,tool_name,scope_key));
CREATE TABLE tool_registry(owner_id uuid NOT NULL REFERENCES users(id),id uuid NOT NULL,name text NOT NULL,version text NOT NULL,descriptor jsonb NOT NULL,descriptor_digest text NOT NULL,provider_name text NOT NULL CHECK(provider_name ~ '^t_[0-9a-f]{32}$'),revision bigint NOT NULL DEFAULT 1,enabled boolean NOT NULL DEFAULT true,PRIMARY KEY(owner_id,id),UNIQUE(owner_id,name),UNIQUE(owner_id,provider_name));
CREATE TABLE tool_calls(id uuid PRIMARY KEY,owner_id uuid NOT NULL,task_id uuid NOT NULL,agent_id uuid,proposal_key text NOT NULL,proposal_digest text NOT NULL,snapshot jsonb NOT NULL,action_hash text NOT NULL CHECK(action_hash ~ '^[0-9a-f]{64}$'),descriptor jsonb NOT NULL,descriptor_digest text NOT NULL,risk jsonb NOT NULL,policy_decision jsonb NOT NULL,state text NOT NULL CHECK(state IN('PROPOSED','WAITING_FOR_APPROVAL','DENIED','SUBMITTED','COMPLETED','FAILED','OUTCOME_UNKNOWN','RECONCILED_APPLIED','RECONCILED_NOT_APPLIED','INVALIDATED')),approval_id uuid,authorization_id uuid UNIQUE,task_fence bigint,dispatch_holder uuid,result jsonb,error_code text,evidence jsonb NOT NULL DEFAULT '[]',submitted_at timestamptz,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),UNIQUE(owner_id,task_id,proposal_key),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id));
CREATE INDEX tool_calls_task ON tool_calls(owner_id,task_id,created_at,id);
CREATE TABLE approvals(id uuid PRIMARY KEY,owner_id uuid NOT NULL,task_id uuid NOT NULL,call_id uuid NOT NULL,snapshot jsonb NOT NULL,action_hash text NOT NULL,risk jsonb NOT NULL,reasons jsonb NOT NULL,preview jsonb NOT NULL,state text NOT NULL DEFAULT 'PENDING' CHECK(state IN('PENDING','APPROVED','DENIED','EXPIRED','CONSUMED')),expires_at timestamptz NOT NULL,decided_at timestamptz,decided_by uuid,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),UNIQUE(owner_id,call_id),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id),FOREIGN KEY(owner_id,call_id) REFERENCES tool_calls(owner_id,id),FOREIGN KEY(owner_id,decided_by) REFERENCES principals(owner_id,id));
ALTER TABLE tool_calls ADD FOREIGN KEY(owner_id,approval_id) REFERENCES approvals(owner_id,id);
CREATE INDEX approvals_owner ON approvals(owner_id,created_at,id);
CREATE FUNCTION immutable_action_binding() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF OLD.snapshot IS DISTINCT FROM NEW.snapshot OR OLD.action_hash IS DISTINCT FROM NEW.action_hash THEN RAISE EXCEPTION 'immutable approval snapshot'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER approval_snapshot_immutable BEFORE UPDATE ON approvals FOR EACH ROW EXECUTE FUNCTION immutable_action_binding();
CREATE TRIGGER call_snapshot_immutable BEFORE UPDATE ON tool_calls FOR EACH ROW EXECUTE FUNCTION immutable_action_binding();
CREATE TABLE artifacts(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),task_id uuid,authorization_id uuid UNIQUE,title text NOT NULL,safe_name text NOT NULL,mime_type text NOT NULL,size bigint NOT NULL CHECK(size BETWEEN 0 AND 10485760),sha256 text NOT NULL CHECK(sha256 ~ '^[0-9a-f]{64}$'),privacy_class text NOT NULL DEFAULT 'PRIVATE',trust_level text NOT NULL DEFAULT 'UNTRUSTED_EXTERNAL',source_references jsonb NOT NULL DEFAULT '[]',storage_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,id),UNIQUE(owner_id,storage_key),FOREIGN KEY(owner_id,task_id) REFERENCES tasks(owner_id,id));
ALTER TABLE notifications DROP CONSTRAINT notifications_owner_id_task_id_key;
ALTER TABLE notifications ADD COLUMN authorization_id uuid UNIQUE;
ALTER TABLE notifications ADD COLUMN related_entity_ids jsonb NOT NULL DEFAULT '[]';
