//! DB-backed marketplace negative tests: tampered digest rejected, unsigned
//! rejected without the dev override, and every install/remove leaves an audit
//! row. Owned test postgres only (default 127.0.0.1:55432 orbit_test). Never
//! the personal deployment.
use serde_json::{Value, json};
use sqlx::PgPool;
use uuid::Uuid;
fn db_url() -> String { std::env::var("DATABASE_URL").unwrap_or_else(|_| "postgres://orbit_test:orbit_test@127.0.0.1:55432/orbit_test".into()) }
async fn pool() -> PgPool { let pool = PgPool::connect(&db_url()).await.expect("owned test postgres reachable"); sqlx::migrate!("../../migrations").run(&pool).await.expect("migrations apply"); pool }
async fn owner(pool: &PgPool) -> orbit_core::OwnerScope { let owner = Uuid::new_v4(); let principal = Uuid::new_v4(); sqlx::query("INSERT INTO users(id,email,display_name,password_hash) VALUES($1,$2,'t','x')").bind(owner).bind(format!("t-{owner}@example.invalid")).execute(pool).await.unwrap(); sqlx::query("INSERT INTO authorization_epochs(owner_id) VALUES($1)").bind(owner).execute(pool).await.unwrap(); sqlx::query("INSERT INTO principals(id,owner_id,principal_type,auth_method,trust_level,source) VALUES($1,$2,'WEB_USER','password','OWNER_AUTHENTICATED','test')").bind(principal).bind(owner).execute(pool).await.unwrap(); orbit_core::OwnerScope { owner_id: owner, principal_id: principal } }
fn hello() -> Value { serde_json::from_str(include_str!("marketplace_hello.json")).unwrap() }
async fn install_row(pool: &PgPool, scope: &orbit_core::OwnerScope, manifest: &Value, dev: bool) -> Result<(), orbit_core::Error> {
    let (sig_valid, _) = orbit_api::marketplace::checked_manifest(manifest, dev)?;
    if !sig_valid && !dev { return Err(orbit_core::Error::Validation("marketplace package is unsigned".into())); }
    let name = manifest.get("name").and_then(Value::as_str).unwrap().to_owned();
    let mut tx = pool.begin().await.map_err(orbit_core::Error::Database)?;
    sqlx::query("SELECT revision FROM authorization_epochs WHERE owner_id=$1 FOR UPDATE").bind(scope.owner_id).fetch_one(&mut *tx).await.map_err(orbit_core::Error::Database)?;
    sqlx::query("INSERT INTO marketplace_installs(id,owner_id,name,version,kind,description,content_digest,publisher_name,publisher_key_id,trust_level,capabilities,sandbox_only) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true) ON CONFLICT(owner_id,name) DO UPDATE SET version=EXCLUDED.version,installed_at=now()").bind(Uuid::new_v4()).bind(scope.owner_id).bind(&name).bind(manifest.get("version").and_then(Value::as_str).unwrap_or_default()).bind(manifest.get("kind").and_then(Value::as_str).unwrap_or_default()).bind(manifest.get("description").and_then(Value::as_str).unwrap_or_default()).bind(manifest.get("content_digest").and_then(Value::as_str).unwrap_or_default()).bind(manifest.pointer("/publisher/name").and_then(Value::as_str).unwrap_or_default()).bind(manifest.pointer("/publisher/key_id").and_then(Value::as_str).unwrap_or_default()).bind(manifest.get("trust_level").and_then(Value::as_str).unwrap_or_default()).bind(manifest.get("requested_capabilities").cloned().unwrap_or(json!({}))).execute(&mut *tx).await.map_err(orbit_core::Error::Database)?;
    orbit_audit::append(&mut tx, scope, Uuid::new_v4(), None, None, "MARKETPLACE_INSTALLED", "owner installed marketplace package (sandbox-only execution)", json!({"name": name})).await?;
    tx.commit().await.map_err(orbit_core::Error::Database)?;
    Ok(())
}
#[tokio::test] async fn tampered_digest_rejected() { let m = hello(); let mut bad = m.clone(); bad["content_digest"] = json!("sha256:a6abcf105bc28a0dd20e0e70c10d35dc8574d4db7978bfb3e0a2eb91cb430dd0"); assert!(orbit_api::marketplace::checked_manifest(&bad, false).unwrap_err().to_string().contains("digest")); }
#[tokio::test] async fn unsigned_rejected_without_override() { let m = hello(); let mut bare = m.clone(); bare.as_object_mut().unwrap().remove("signature"); assert!(orbit_api::marketplace::checked_manifest(&bare, false).is_err()); assert!(!orbit_api::marketplace::checked_manifest(&bare, true).unwrap().0); }
#[tokio::test] async fn install_and_remove_leave_audit_rows() { let pool = pool().await; let scope = owner(&pool).await; let m = hello(); install_row(&pool, &scope, &m, false).await.unwrap(); let row: Option<String> = sqlx::query_scalar("SELECT name FROM marketplace_installs WHERE owner_id=$1 AND name='hello-skill'").bind(scope.owner_id).fetch_optional(&pool).await.unwrap(); assert_eq!(row.as_deref(), Some("hello-skill")); let mut tx = pool.begin().await.unwrap(); sqlx::query("DELETE FROM marketplace_installs WHERE owner_id=$1 AND name='hello-skill'").bind(scope.owner_id).execute(&mut *tx).await.unwrap(); orbit_audit::append(&mut tx, &scope, Uuid::new_v4(), None, None, "MARKETPLACE_REMOVED", "owner removed marketplace package", json!({"name": "hello-skill"})).await.unwrap(); tx.commit().await.unwrap(); let ops: Vec<String> = sqlx::query_scalar("SELECT operation FROM audit_events WHERE owner_id=$1 AND operation IN('MARKETPLACE_INSTALLED','MARKETPLACE_REMOVED') ORDER BY sequence").bind(scope.owner_id).fetch_all(&pool).await.unwrap(); assert_eq!(ops, vec!["MARKETPLACE_INSTALLED".to_owned(), "MARKETPLACE_REMOVED".to_owned()]); }
#[tokio::test] async fn over_broad_capabilities_flagged() { let mut m = hello(); m["requested_capabilities"] = json!({"network":{"hosts":["exfil.example"],"egress":true},"filesystem":{"scopes":["workspace"],"read_only":false},"secrets":["api-key"],"tools":["fetch_note"]}); let flags = orbit_api::marketplace::over_broad_flags(&m); assert_eq!(flags.len(), 4, "egress + secrets + tools + writable must surface: {flags:?}"); }
